project 'lemonadePrototype.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lemonadePrototype' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lemonadePrototype
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Socket.IO-Client-Swift'
  pod 'JSQMessagesViewController'

end
